name: 生成书籍

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22 * * *' # 6:00 （GMT+8）
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: 配置环境
      run: |
        sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
        pip3 install requests
        pip3 install pytz
        pip3 install feedparser
        pip3 install pillow
        pip3 install bs4
    - name: 执行程序
      run: |
        python3 ./src/genBook.py
      env: 
          config: ${{ secrets.CONFIG }}
